services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: AI-Courtroom

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-courtroom-server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
    environment:
      MONGODB_URL: mongodb://mongodb:27017

volumes:
  mongodb_data:
