# app/models/person.py
import uuid
from enum import Enum

from pydantic import BaseModel, Field


class PartyRole(str, Enum):
    APPLICANT = "applicant"
    NON_APPLICANT = "non_applicant"


class PartyInvolved(BaseModel):
    """Model for parties involved in a case"""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    role: PartyRole
    occupation: str | None = None
    age: int | None = None
    address: str | None = None
    bio: str | None = None  # Detailed background generated by LLM
