# app/models/person.py
from typing import Optional
from pydantic import Field, BaseModel
from datetime import datetime
from enum import Enum
from app.utils.datetime import get_current_datetime
import uuid

class PartyRole(str, Enum):
    APPLICANT = "applicant"
    NON_APPLICANT = "non_applicant"


class PartyInvolved(BaseModel):
    """Model for parties involved in a case"""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    role: PartyRole
    occupation: Optional[str] = None
    age: Optional[int] = None
    address: Optional[str] = None
    bio: Optional[str] = None  # Detailed background generated by LLM


class PartyChatMessage(BaseModel):
    """Model for chat messages with parties involved"""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    sender: str  # 'user' or 'party'
    content: str
    timestamp: datetime = Field(default_factory=get_current_datetime)
