# app/models/person.py
from typing import Optional
from pydantic import Field, BaseModel
from datetime import datetime
from enum import Enum
from app.utils.datetime import get_current_datetime
import uuid


class PersonRole(str, Enum):
    APPLICANT = "applicant"
    NON_APPLICANT = "non_applicant"


class PersonInvolved(BaseModel):
    """Model for people involved in a case"""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    role: PersonRole
    occupation: Optional[str] = None
    age: Optional[int] = None
    address: Optional[str] = None
    bio: Optional[str] = None  # Detailed background generated by LLM


class PersonChatMessage(BaseModel):
    """Model for chat messages with people involved"""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    sender: str  # 'user' or 'person'
    content: str
    timestamp: datetime = Field(default_factory=get_current_datetime)
